=== melovictor/gamebooks/core/support/src/main/resources/xsds/ff-enemies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gamebooks.zagor.hu" version="1.0" xmlns="http://gamebooks.zagor.hu">
  <xs:element name="enemies">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="enemy" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="enemy">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="commonName" type="xs:string" use="optional" />
      <xs:attribute name="skill" type="xs:integer" use="required" />
      <xs:attribute name="stamina" type="xs:integer" use="required" />
      <xs:attribute name="staminaDamage" type="xs:integer" default="2" />
      <xs:attribute name="staminaDamageWhenHit" type="xs:integer" default="0" />
      <xs:attribute name="staminaAutoDamage" type="xs:integer" default="0" />
      <xs:attribute name="staminaDamageWhileInactive" type="xs:integer" default="0" />
      <xs:attribute name="skillDamage" type="xs:integer" default="0" />
      <xs:attribute name="damageAbsorption" type="xs:integer" default="0" />
      <xs:attribute name="damageAbsorptionEdged" type="xs:integer" default="0" />
      <xs:attribute name="resurrectable" type="xs:boolean" default="false" />
      <xs:attribute name="killableByNormal" type="xs:boolean" default="true" />
      <xs:attribute name="killableByMagical" type="xs:boolean" default="true" />
      <xs:attribute name="killableByBlessed" type="xs:boolean" default="true" />
      <xs:attribute name="fleeAtStamina" type="xs:integer" default="0" />
      <xs:attribute name="fleeAtRound" type="xs:integer" />
      <xs:attribute name="same" type="xs:string" />

      <xs:attribute name="attackStrength" type="xs:integer">
        <xs:annotation>
          <xs:documentation>
            If this value is set, it ensures that the result of the roll will be this amount.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="attackStrengthBonus" type="xs:integer" />

      <xs:attribute name="startAtRound" type="xs:integer" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjkzf1p1enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy name="Tolvaj" id="1" stamina="6" skill="7" />
  <enemy name="Első Denevér" id="2" stamina="7" skill="5" />
  <enemy name="Második Denevér" id="3" stamina="6" skill="6" />
  <enemy name="Xlaia" id="4" stamina="7" skill="8" />
  <enemy name="Fényimádók" id="5" stamina="11" skill="9" />
  <enemy name="Hobgoblin" id="6" stamina="8" skill="7" />
  <enemy name="Óriáspók" id="7" stamina="5" skill="9" />
  <enemy name="Első Ork" id="8" stamina="6" skill="5" />
  <enemy name="Második Ork" id="9" stamina="5" skill="6" />
  <enemy name="Első Sündisznó" id="10" stamina="5" skill="7" staminaDamage="3" />
  <enemy name="Második Sündisznó" id="11" stamina="5" skill="8" staminaDamage="3" />
  <enemy name="Törpe" id="12" stamina="5" skill="8" />
  <enemy name="Tükörkép" id="13" stamina="99" skill="99"/>
  <enemy name="Galon" id="14" stamina="8" skill="12"/>
  <enemy name="Iszapsárkány" id="15" stamina="5" skill="9"/>
  <enemy name="Iszapsárkány" id="16" stamina="6" skill="10"/>
  <enemy name="Első Iszapsárkány" id="17" stamina="5" skill="9"/>
  <enemy name="Második Iszapsárkány" id="18" stamina="6" skill="10"/>
  

</enemies>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjkzf1p3enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy id="1" name="Első Városi Őr" skill="7" stamina="4" />
  <enemy id="2" name="Második Városi Őr" skill="6" stamina="6" />
  <enemy id="3" name="Nomád Kereskedő" skill="5" stamina="6" />
  <enemy id="4" name="Első Hobgoblin" skill="6" stamina="6" />
  <enemy id="5" name="Második Hobgoblin" skill="5" stamina="7" />
  <enemy id="6" name="Első Hobgoblin" skill="7" stamina="4" />
  <enemy id="7" name="Második Hobgoblin" skill="6" stamina="6" />
  <enemy id="8" name="Harmadik Hobgoblin" skill="7" stamina="5" />
  <enemy id="9" name="Negyedik Hobgoblin" skill="6" stamina="4" />
  <enemy id="10" name="Thoul" skill="9" stamina="7" />
  <enemy id="11" name="Mágus-Kormányzó" skill="10" stamina="12" />
  <enemy id="12" name="Goblin" skill="7" stamina="6" />
  <enemy id="13" name="Gnoll" skill="8" stamina="4" />
  <enemy id="14" name="Gyíkember" skill="7" stamina="7" />
  <enemy id="15" name="Első Hobgoblin Őr" skill="6" stamina="6" />
  <enemy id="16" name="Második Hobgoblin Őr" skill="5" stamina="7" />
  <enemy id="17" name="Éjghoul" skill="8" stamina="7" />
  <enemy id="18" name="Harci Macska" skill="9" stamina="8" />
  <enemy id="19" name="Lauper" skill="10" stamina="6" />
  <enemy id="20" name="Sziklabéka" skill="8" stamina="6" />
  <enemy id="21" name="Harci Macska" skill="9" stamina="8" />
  <enemy id="22" name="Lauper" skill="10" stamina="6" />
  <enemy id="23" name="Első Lauper" skill="6" stamina="6" />
  <enemy id="24" name="Harci Macska" skill="8" stamina="7" />
  <enemy id="25" name="Második Lauper" skill="9" stamina="5" />
  <enemy id="26" name="Első Lauper" skill="7" stamina="5" />
  <enemy id="27" name="Második Lauper" skill="6" stamina="6" />
  <enemy id="28" name="Lauper" skill="7" stamina="6" />
  <enemy id="29" name="Első Gyíkember" skill="8" stamina="8" />
  <enemy id="30" name="Második Gyíkember" skill="9" stamina="8" />
  <enemy id="31" name="Harmadik Gyíkember" skill="8" stamina="7" />
  <enemy id="32" name="Első Bogármedve Őr" skill="8" stamina="8" />
  <enemy id="33" name="Második Bogármedve Őr" skill="8" stamina="9" />
  <enemy id="34" name="Gyíkember" skill="8" stamina="6" />
  <enemy id="35" name="Bronzgólem" skill="10" stamina="9" staminaDamageWhenHit="1" />
  <enemy id="36" name="Bronzgólem" skill="11" stamina="9" staminaDamageWhenHit="1" />
  <enemy id="37" name="Lauper" skill="7" stamina="7" />
  <enemy id="38" name="Ork" skill="7" stamina="6" />
  <enemy id="39" name="Első Nomád" skill="6" stamina="5" />
  <enemy id="40" name="Második Nomád" skill="5" stamina="6" />
  <enemy id="41" name="Bogármedve" skill="9" stamina="7" />
  <enemy id="42" name="Első Goblin" skill="5" stamina="5" />
  <enemy id="43" name="Második Goblin" skill="5" stamina="4" />
  <enemy id="44" name="Tűzóriás" skill="12" stamina="18" />
  <enemy id="45" name="Óriás Karvaly" skill="9" stamina="9" />
  <enemy id="46" name="Óriás Ölyv" skill="10" stamina="12" />
  <enemy id="47" name="Kígyók" skill="6" stamina="6" staminaDamage="4" />
  <enemy id="48" name="Dervis" skill="7" stamina="6" />
  <enemy id="49" name="Első Karolópók" skill="5" stamina="7" />
  <enemy id="50" name="Második Karolópók" skill="7" stamina="6" />


</enemies>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk17enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy stamina="7" skill="7" id="1" name="Első Kaméleonita" />
  <enemy stamina="6" skill="6" id="2" name="Második Kaméleonita" />
  <enemy stamina="6" skill="7" id="3" name="Harmadik Kaméleonita" />
  <enemy stamina="5" skill="10" id="4" name="Első Rad-Hulk" />
  <enemy stamina="6" skill="10" id="5" name="Második Rad-Hulk" />
  <enemy stamina="5" skill="6" id="6" name="Ork" />
  <enemy stamina="5" skill="6" id="7" name="Első Ork" />
  <enemy stamina="6" skill="6" id="8" name="Második Ork" />
  <enemy stamina="5" skill="6" id="9" name="Harmadik Ork" />
  <enemy stamina="6" skill="6" id="10" name="Első Ork" />
  <enemy stamina="5" skill="6" id="11" name="Második Ork" />
  <enemy stamina="9" skill="8" id="12" name="Farkasember" />
  <enemy stamina="6" skill="5" id="13" name="Csontok Őrzője" />
  <enemy stamina="5" skill="5" id="14" name="Első Goblin" />
  <enemy stamina="6" skill="5" id="15" name="Második Goblin" />
  <enemy stamina="5" skill="6" id="16" name="Harmadik Goblin" />
  <enemy stamina="6" skill="6" id="17" name="Negyedik Goblin" />
  <enemy stamina="4" skill="5" id="18" name="Első Óriás Tűzbogár" />
  <enemy stamina="4" skill="5" id="19" name="Második Óriás Tűzbogár" />
  <enemy stamina="10" skill="9" id="20" name="Erdei Démon" />
  <enemy stamina="10" skill="10" id="21" name="Griffin" />
  <enemy stamina="9" skill="8" id="22" name="Agyaggólem" />
  <enemy stamina="9" skill="8" id="23" name="Farkasember" />
  <enemy stamina="10" skill="10" id="24" name="Kentaur" />
  <enemy stamina="10" skill="9" id="25" name="Dombi Óriás" />
  <enemy stamina="5" skill="6" id="26" name="Vad Dombi Ember" />
  <enemy stamina="6" skill="5" id="27" name="Démoni Szolga" />
  <enemy stamina="6" skill="6" id="28" name="Démonivadék" killableByNormal="false" />
  <enemy stamina="7" skill="8" id="29" name="Majomember" fleeAtRound="3" />
  <enemy stamina="5" skill="6" id="30" name="Első Csontváz" />
  <enemy stamina="6" skill="6" id="31" name="Második Csontváz" />
  <enemy stamina="6" skill="5" id="32" name="Harmadik Csontváz" />
  <enemy stamina="7" skill="7" id="33" name="Törpe" />
  <enemy stamina="5" skill="4" id="34" name="Vasevő" staminaDamage="0" skillDamage="1" />
  <enemy stamina="9" skill="9" id="35" name="Első Doragar" />
  <enemy stamina="10" skill="9" id="36" name="Második Doragar" />
  <enemy stamina="9" skill="8" id="37" name="Barlangi Troll" />
  <enemy stamina="24" skill="12" id="38" name="Gargantis" />
  <enemy stamina="6" skill="5" id="39" name="Patkányember" />
  <enemy stamina="4" skill="5" id="40" name="Vámpír Denevér" />
  <enemy stamina="6" skill="7" id="41" name="Vad Elf" />
  <enemy stamina="7" skill="8" id="42" name="Démoni Szolga" />
  <enemy stamina="8" skill="8" id="43" name="Pokolfenevad" />
  <enemy stamina="4" skill="6" id="44" name="Első Láva Démon" />
  <enemy stamina="4" skill="5" id="45" name="Második Láva Démon" />
  <enemy stamina="4" skill="6" id="46" name="Harmadik Láva Démon" />
  <enemy stamina="6" skill="6" id="47" name="Zombi" />
  <enemy stamina="20" skill="12" id="48" name="Razaak" />



  <enemy stamina="10" skill="10" id="101" name="Symm" startAtRound="0" />
  <enemy stamina="10" skill="9" id="102" name="Borri" startAtRound="0" />

</enemies>

=== melovictor/gamebooks/books/wm/tdcoa/wm6/src/main/resources/wm6enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy name="Ice Warrior" id="1" stamina="8" skill="7" />
  <enemy name="Macra" id="2" stamina="12" skill="8" staminaDamage="3" />
  <enemy name="Granzork" id="3" stamina="10" skill="7" />
  <enemy name="Astromancer" id="4" stamina="6" skill="9" fleeAtRound="2" />
  <enemy name="Dinosaur" id="5" stamina="16" skill="7" />
  <enemy name="Man" id="6" stamina="12" skill="9" />
  <enemy name="Zombie" id="7" stamina="7" skill="6" />
  <enemy name="Imp" id="8" stamina="5" skill="10" />
  <enemy name="Creepers" id="9" stamina="4" skill="7" staminaDamage="0" staminaAutoDamage="2" />
  <enemy name="Forest Demon" id="10" stamina="8" skill="8" />
  <enemy name="Crystal Statue" id="11" stamina="9" skill="9" damageAbsorption="1" />
  <enemy name="First Walking Mouth" id="12" stamina="7" skill="7" />
  <enemy name="Second Walking Mouth" id="13" stamina="7" skill="7" />
  <enemy name="Sand Squid" id="14" stamina="9" skill="8" />
  <enemy name="Devil Hound" id="15" stamina="8" skill="7" fleeAtRound="4" />
  <enemy name="Hound-Master" id="19" stamina="10" skill="8" />
  <enemy name="Traskannd" id="20" stamina="14" skill="11" fleeAtRound="2" />
  <enemy name="Denrec" id="21" stamina="2" skill="9" />
  <enemy name="Hand" id="22" stamina="2" skill="11" fleeAtRound="3" />
  <enemy name="Anakendis" id="23" stamina="20" skill="12" killableByNormal="false" />
  <enemy name="Anakendis" id="24" stamina="20" skill="12" killableByNormal="false" fleeAtRound="2" />
  <enemy name="Anakendis" id="25" stamina="14" skill="8" />
</enemies>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk2enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy id="1" name="Ork" skill="6" stamina="5" />
  <enemy id="2" name="Ork" skill="6" stamina="4" />
  <enemy id="3" name="Kígyó" skill="5" stamina="2" />
  <enemy stamina="4" skill="5" id="4" name="Első Ork" />
  <enemy stamina="5" skill="5" id="5" name="Második Ork" />
  <enemy stamina="6" skill="7" id="6" name="Ork Törzsfőnök" />
  <enemy stamina="3" skill="7" id="7" name="Szolga" />
  <enemy stamina="5" skill="5" id="8" name="Első Goblin" />
  <enemy stamina="6" skill="5" id="9" name="Második Goblin" />
  <enemy stamina="4" skill="6" id="10" name="Első Ork" />
  <enemy stamina="3" skill="5" id="11" name="Második Ork" />
  <enemy stamina="4" skill="6" id="12" name="Harmadik Ork" />
  <enemy stamina="2" skill="5" id="13" name="Negyedik Ork" />
  <enemy stamina="4" skill="4" id="14" name="Ötödik Ork" />
  <enemy id="15" name="Ogre" skill="8" stamina="10" />
  <enemy id="16" name="Szárnyas Gremlin" skill="5" stamina="7" />
  <enemy stamina="4" skill="6" id="17" name="Kéz" />
  <enemy stamina="7" skill="7" id="18" name="Óriás Homokhernyó" />
  <enemy id="19" name="Troll" skill="8" stamina="8" />
  <enemy stamina="4" skill="5" id="20" name="Első Patkány" />
  <enemy stamina="3" skill="6" id="21" name="Második Patkány" />
  <enemy stamina="5" skill="5" id="22" name="Harmadik Patkány" />
  <enemy stamina="9" skill="8" id="23" name="Óriás" />
  <enemy stamina="10" skill="10" id="24" name="Vas Küklopsz" />
  <enemy stamina="6" skill="7" id="25" name="Barbár" />
  <enemy stamina="8" skill="7" id="26" name="Óriás Pók" />
  <enemy stamina="6" skill="7" id="27" name="Első Ősember" />
  <enemy stamina="4" skill="6" id="28" name="Második Ősember" />
  <enemy stamina="6" skill="6" id="29" name="Denevérek" />
  <enemy stamina="5" skill="8" id="30" name="Patkányember" resurrectable="true" />
  <enemy stamina="6" skill="7" id="31" name="Krokodil" fleeAtRound="2" />
  <enemy stamina="5" skill="5" id="32" name="Piranhák" resurrectable="true" />
  <enemy stamina="1" skill="5" id="33" name="Piranhák" resurrectable="true" />
  <enemy stamina="5" skill="5" id="34" name="Piranhák" resurrectable="true" />
  <enemy stamina="6" skill="7" id="35" name="Kutya" />
  <enemy stamina="8" skill="8" id="36" name="Farkasember" />
  <enemy stamina="5" skill="7" id="37" name="A Csontvázak Vezére" />
  <enemy stamina="5" skill="6" id="38" name="Első Csontváz" />
  <enemy stamina="6" skill="6" id="39" name="Második Csontváz" />
  <enemy stamina="6" skill="5" id="40" name="Harmadik Csontváz" />
  <enemy stamina="5" skill="5" id="41" name="Negyedik Csontváz" />
  <enemy stamina="5" skill="5" id="42" name="Harmadik Csontváz" />
  <enemy stamina="6" skill="9" id="43" name="Lidérc" killableByNormal="false" killableByMagical="false" />
  <enemy stamina="6" skill="7" id="44" name="Zombi" />
  <enemy stamina="6" skill="6" id="45" name="Zombi kaszával" />
  <enemy stamina="6" skill="6" id="46" name="Zombi csákánnyal" />
  <enemy stamina="5" skill="6" id="47" name="Zombi bárddal" />
  <enemy stamina="10" skill="10" id="48" name="Vámpír" />
  <enemy stamina="7" skill="8" id="49" name="Ghoul" />
  <enemy stamina="4" skill="7" id="50" name="Első Törpe" />
  <enemy stamina="6" skill="6" id="51" name="Második Törpe" />
  <enemy stamina="5" skill="7" id="52" name="Harmadik Törpe" />
  <enemy stamina="5" skill="7" id="53" name="Negyedik Törpe" />
  <enemy stamina="9" skill="9" id="54" name="Minotaurusz" />
  <enemy stamina="12" skill="10" id="55" name="Sárkány" />
  <enemy stamina="18" skill="11" id="56" name="Varázsló" />
  <enemy stamina="12" skill="7" id="57" name="Varázsló" />
  <enemy stamina="18" skill="11" id="58" name="Varázsló" damageAbsorption="-1" />



  <enemy stamina="3" skill="5" id="91" name="Goblin" resurrectable="true" />
  <enemy stamina="3" skill="6" id="92" name="Ork" resurrectable="true" />
  <enemy stamina="4" skill="6" id="93" name="Gremlin" resurrectable="true" />
  <enemy stamina="4" skill="5" id="94" name="Óriás Patkány" resurrectable="true" />
  <enemy stamina="5" skill="6" id="95" name="Csontváz" resurrectable="true" />
  <enemy stamina="4" skill="8" id="96" name="Troll" resurrectable="true" />




</enemies>

=== melovictor/gamebooks/books/ff/toc/kjk9/src/main/resources/kjk9enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy id="1" name="Csonttörő" skill="9" stamina="10" />
  <enemy id="2" name="Keleti Ember" skill="10" stamina="8" />
  <enemy name="Rabszolga" id="3" stamina="8" skill="9" />
  <enemy name="Küzdő Rabszolga" id="4" stamina="8" skill="8" />
  <enemy name="Délvidéki Ember" id="5" stamina="10" skill="10" />
  <enemy name="Pokolkutya" id="6" stamina="6" skill="7" />
  <enemy name="Lopakodó" id="7" stamina="6" skill="6" />
  <enemy name="Első Vámpír Denevér" id="8" stamina="5" skill="5" staminaDamageWhileInactive="1" />
  <enemy name="Második Vámpír Denevér" id="9" stamina="4" skill="5" staminaDamageWhileInactive="1" />
  <enemy name="Hidegkarom" id="10" stamina="11" skill="10" />
  <enemy name="Csontördög" id="11" stamina="8" skill="10" />
  <enemy name="Első Ork" id="12" stamina="5" skill="6" />
  <enemy name="Második Ork" id="13" stamina="6" skill="6" />
  <enemy name="Mutáns Ork" id="14" stamina="7" skill="7" />
  <enemy name="Óriáspók" id="15" stamina="8" skill="7" />
  <enemy name="Első Patkány" id="16" stamina="2" skill="3" />
  <enemy name="Második Patkány" id="17" stamina="2" skill="2" />
  <enemy name="Harmadik Patkány" id="18" stamina="2" skill="3" />
  <enemy name="Negyedik Patkány" id="19" stamina="2" skill="3" />
  <enemy name="Ötödik Patkány" id="20" stamina="2" skill="4" />
  <enemy name="Lícs Királynő" id="21" stamina="9" skill="9" />
  <enemy name="Óriás Százlábú" id="22" stamina="7" skill="9" />
  <enemy name="Barlangi Ember" id="23" stamina="10" skill="7" staminaDamage="0" damageAbsorption="3" />
  <enemy name="Csontváz Király" id="24" stamina="7" skill="9" damageAbsorptionEdged="1" />
  <enemy name="Vérféreg" id="25a" stamina="6" skill="4" staminaAutoDamage="2" />
  <enemy name="Vérféreg" id="25b" stamina="6" skill="4" />
  <enemy name="Xoroa Harcos" id="26" stamina="11" skill="10" />
  <enemy name="Kétfejű Kutya, Első Fej" commonName="Kétfejű Kutya" id="27a" stamina="5" skill="6" />
  <enemy name="Kétfejű Kutya, Második Fej" commonName="Kétfejű Kutya" id="27b" stamina="5" skill="6" />
  <enemy name="Agyaras" id="28" stamina="6" skill="6" />
  <enemy name="Káoszbajnok" id="29a" stamina="12" skill="11" />
  <enemy name="Káoszbajnok" id="29b" stamina="10" skill="11" />
  <enemy name="Első Xoroa Harcos" id="30" stamina="10" skill="10" />
  <enemy name="Második Xoroa Harcos" id="31" stamina="11" skill="9" />
  <enemy name="Harmadik Xoroa Harcos" id="32" stamina="11" skill="10" />
  <enemy name="Negyedik Xoroa Harcos" id="33" stamina="10" skill="10" />
  <enemy name="Nyelv" id="34" stamina="6" skill="5" />
  <enemy name="Tentallus" id="35" stamina="12" skill="8" />
  <enemy name="Bálvány" id="36" stamina="6" skill="9" killableByNormal="false" />
  <enemy name="Dombi Troll" id="37" stamina="10" skill="9" />
  <enemy name="Keleti Hadúr" id="38" stamina="9" skill="10" />
  <enemy name="Tűzördög" id="39" stamina="4" skill="9" />
  <enemy name="Tűzdémon" id="40" stamina="10" skill="10" />
  <enemy name="Lord Carnuss" id="41" stamina="10" skill="10" />

</enemies>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk10enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy stamina="9" skill="8" id="1" name="Fehér Nőstényfarkas" />
  <enemy stamina="9" skill="8" id="2" name="Grendel" />
  <enemy stamina="6" skill="5" id="3" name="Első Ork" />
  <enemy stamina="4" skill="5" id="4" name="Második Ork" />
  <enemy stamina="7" skill="7" id="5" name="Ork Vezér" />
  <enemy stamina="20" skill="8" id="6" name="Gyilkos Fűz" />
  <enemy stamina="10" skill="8" id="7" name="Kapitány" />
  <enemy stamina="8" skill="6" id="8" name="Elvira" />
  <enemy stamina="8" skill="7" id="9" name="Láthatatlan Támadó" />
  <enemy stamina="15" skill="10" id="10" name="Halállovag" />

</enemies>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjv4enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy stamina="6" skill="7" id="1" name="Bűzös Borz" />
  <enemy stamina="11" skill="9" id="2" name="Madárember" />
  <enemy stamina="7" skill="7" id="3" name="Farkas" />
  <enemy stamina="2" skill="7" id="4" name="Őr" />
  <enemy stamina="6" skill="8" id="5" name="Második Őr" />
  <enemy stamina="7" skill="7" id="6" name="Első Őr" />
  <enemy stamina="7" skill="6" id="7" name="Második Őr" />
  <enemy stamina="8" skill="7" id="8" name="Harmadik Őr" />
  <enemy stamina="7" skill="8" id="9" name="Negyedik Őr" />
  <enemy stamina="6" skill="7" id="10" name="Első Fekete Elf" />
  <enemy stamina="7" skill="7" id="11" name="Második Fekete Elf" />
  <enemy stamina="6" skill="6" id="12" name="Harmadik Fekete Elf" />
  <enemy stamina="6" skill="8" id="13" name="Első Őr" />
  <enemy stamina="7" skill="7" id="14" name="Második Őr" />
  <enemy stamina="6" skill="8" id="15" name="Őr" />

</enemies>
