=== melovictor/gamebooks/core/support/src/main/resources/xsds/ff-enemies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gamebooks.zagor.hu" version="1.0" xmlns="http://gamebooks.zagor.hu">
  <xs:element name="enemies">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="enemy" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="enemy">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="commonName" type="xs:string" use="optional" />
      <xs:attribute name="skill" type="xs:integer" use="required" />
      <xs:attribute name="stamina" type="xs:integer" use="required" />
      <xs:attribute name="staminaDamage" type="xs:integer" default="2" />
      <xs:attribute name="staminaDamageWhenHit" type="xs:integer" default="0" />
      <xs:attribute name="staminaAutoDamage" type="xs:integer" default="0" />
      <xs:attribute name="staminaDamageWhileInactive" type="xs:integer" default="0" />
      <xs:attribute name="skillDamage" type="xs:integer" default="0" />
      <xs:attribute name="damageAbsorption" type="xs:integer" default="0" />
      <xs:attribute name="damageAbsorptionEdged" type="xs:integer" default="0" />
      <xs:attribute name="resurrectable" type="xs:boolean" default="false" />
      <xs:attribute name="killableByNormal" type="xs:boolean" default="true" />
      <xs:attribute name="killableByMagical" type="xs:boolean" default="true" />
      <xs:attribute name="killableByBlessed" type="xs:boolean" default="true" />
      <xs:attribute name="fleeAtStamina" type="xs:integer" default="0" />
      <xs:attribute name="fleeAtRound" type="xs:integer" />
      <xs:attribute name="same" type="xs:string" />

      <xs:attribute name="attackStrength" type="xs:integer">
        <xs:annotation>
          <xs:documentation>
            If this value is set, it ensures that the result of the roll will be this amount.
          </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="attackStrengthBonus" type="xs:integer" />

      <xs:attribute name="startAtRound" type="xs:integer" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk15enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy stamina="6" skill="6" id="1" name="Első Csáp" />
  <enemy stamina="6" skill="6" id="2" name="Második Csáp" />
  <enemy stamina="6" skill="6" id="3" name="Harmadik Csáp" />
  <enemy stamina="6" skill="6" id="4" name="Negyedik Csáp" />
  <enemy stamina="6" skill="6" id="5" name="Ötödik Csáp" />
  <enemy stamina="10" skill="6" id="6" name="Első Feketeszívű" />
  <enemy stamina="10" skill="7" id="7" name="Második Feketeszívű" />
  <enemy stamina="8" skill="6" id="8" name="Első Spriggen" />
  <enemy stamina="8" skill="7" id="9" name="Második Spriggen" />
  <enemy stamina="10" skill="7" id="10" name="Erdei Elf-főnök" />
  <enemy stamina="12" skill="9" id="11" name="Lidérc" />
  <enemy stamina="12" skill="5" id="12" name="Denevérek" />
  <enemy stamina="11" skill="9" id="13" name="Nandi-medve" />
  <enemy stamina="10" skill="9" id="14" name="Doragar" />
  <enemy stamina="6" skill="5" id="15" name="Élősködők" />
  <enemy stamina="8" skill="7" id="16" name="Törpe Ork" fleeAtRound="2" />
  <enemy stamina="10" skill="6" id="17" name="Törpe Ork" fleeAtRound="5" />
  <enemy stamina="8" skill="5" id="18" name="Második Törpe Ork" />
  <enemy stamina="10" skill="6" id="19" name="Első Törpe Ork" />
  <enemy stamina="12" skill="9" id="20" name="Pokoltűz Szellem" />
  <enemy stamina="12" skill="11" id="21" name="Kardfogú Tigris" fleeAtRound="4" />
  <enemy stamina="4" skill="4" id="22" name="Köpködő Vipera" />
  <enemy stamina="8" skill="5" id="23" name="Első Csontváz" />
  <enemy stamina="8" skill="5" id="24" name="Második Csontváz" />
  <enemy stamina="6" skill="7" id="25" name="Árnyékszörny" damageAbsorption="1" />
  <enemy stamina="8" skill="6" id="26" name="Vadmacska" />
  <enemy stamina="8" skill="5" id="27" name="Első Mordida" />
  <enemy stamina="10" skill="7" id="28" name="Második Mordida" />
  <enemy stamina="11" skill="9" id="29" name="Dombi Óriás" />
  <enemy stamina="12" skill="7" id="30" name="Óriás Vérsólyom" />
  <enemy stamina="14" skill="6" id="31" name="Vérszívó Pók" />
  <enemy stamina="8" skill="7" id="32" name="Aligátor" />
  <enemy stamina="10" skill="7" id="33" name="Aligátor" />
  <enemy stamina="6" skill="7" id="34" name="Kiméra" staminaDamage="2" staminaAutoDamage="1" />
  <enemy stamina="10" skill="8" id="35" name="Első Törzsi Harcos" />
  <enemy stamina="12" skill="7" id="36" name="Második Törzsi Harcos" />
  <enemy stamina="12" skill="6" id="37" name="Hóbocs" fleeAtStamina="11" />
  <enemy stamina="10" skill="10" id="38" name="Jégsárkány" />
  <enemy stamina="14" skill="10" id="39" name="Jégsárkány" />
  <enemy stamina="13" skill="7" id="40" name="Chion" />
  <enemy stamina="8" skill="7" id="41" name="Kezek" />
  <enemy stamina="6" skill="11" id="42" name="Morgana" damageAbsorption="1" />
  <enemy stamina="10" skill="8" id="43" name="Ifor Tynin" />
  <enemy stamina="10" skill="8" id="44" name="Első Törzsi Harcos" />
  <enemy stamina="12" skill="7" id="45" name="Második Törzsi Harcos" />
  <enemy stamina="6" skill="6" id="46" name="Első Csáp" />
  <enemy stamina="6" skill="6" id="47" name="Második Csáp" />
  <enemy stamina="6" skill="6" id="48" name="Harmadik Csáp" />
  <enemy stamina="6" skill="6" id="49" name="Negyedik Csáp" />
  <enemy stamina="6" skill="6" id="50" name="Ötödik Csáp" />







</enemies>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk14enemies.xml
<?xml version="1.0" encoding="utf-8" ?>
<enemies xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-enemies.xsd">
  <enemy name="Púpos" id="1" stamina="7" skill="7" fleeAtStamina="4" />
  <enemy name="Zombi" id="2" stamina="6" skill="7" />
  <enemy name="Láthatatlan ellenfél" id="3" stamina="4" skill="10" />
  <enemy name="Első Zombi" id="4" stamina="6" skill="7" />
  <enemy name="Második Zombi" id="5" stamina="6" skill="6" />
  <enemy name="Fehér hajú férfi" id="6" stamina="9" skill="7" />
  <enemy name="Vezér" id="7" stamina="9" skill="8" />
  <enemy name="Az Úr szolgálója" id="10" stamina="9" skill="8" />
  <enemy name="Első férfi" id="11" stamina="8" skill="7" />
  <enemy name="Második férfi" id="12" stamina="9" skill="8" />
  <enemy name="Fehér köntöst viselő mester" id="13" stamina="9" skill="7" fleeAtStamina="2" />
  <enemy name="Púpos" id="14" stamina="7" skill="7" fleeAtStamina="6" />
  <enemy name="Első Tűzmanó" id="15" stamina="4" skill="7" staminaDamage="3" />
  <enemy name="Második Tűzma" id="16" stamina="3" skill="7" staminaDamage="3" />
  <enemy name="Ghoul" id="17" stamina="7" skill="8" />
  <enemy name="Púpos" id="18" stamina="7" skill="7" />
  <enemy name="Púpos" id="19" stamina="7" skill="7" />
  <enemy name="Dán dog" id="20" stamina="5" skill="7" />
  <enemy name="Második Dán dog" id="21" stamina="6" skill="6" />
  <enemy name="Harmadik Dán dog" id="22" stamina="5" skill="6" />
  <enemy name="Első Dán dog" id="23" stamina="6" skill="7" />
  <enemy name="Második Dán dog" id="24" stamina="6" skill="6" />
  <enemy name="Denevérek" id="25" stamina="4" skill="4" />
  <enemy name="Ghoul" id="26" stamina="7" skill="8" />
  <enemy name="Első Csontváz" id="27" stamina="6" skill="6" />
  <enemy name="Második Csontváz" id="28" stamina="6" skill="7" />
  <enemy name="Az Ördög híve" id="29" stamina="7" skill="8" />
  <enemy name="Drumer grófja" id="30" stamina="10" skill="9" />
  <enemy name="Franklins" id="31" stamina="8" skill="8" />
  <enemy name="Pokoldémon" id="32" stamina="12" skill="14" killableByNormal="false" />

</enemies>
