=== melovictor/gamebooks/core/support/src/main/resources/xsds/ff-items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gamebooks.zagor.hu" version="1.0" xmlns="http://gamebooks.zagor.hu">
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="item" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="name" type="xs:string" use="required" />

      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="common" />
            <xs:enumeration value="info" />
            <xs:enumeration value="shadow" />
            <xs:enumeration value="immediate" />

            <xs:enumeration value="weapon1" />
            <xs:enumeration value="weapon2" />
            <xs:enumeration value="shooting" />
            <xs:enumeration value="shield" />
            <xs:enumeration value="ring" />
            <xs:enumeration value="necklace" />
            <xs:enumeration value="boots" />
            <xs:enumeration value="armour" />
            <xs:enumeration value="helmet" />
            <xs:enumeration value="bracelet" />
            <xs:enumeration value="cloak" />
            <xs:enumeration value="brooch" />
            <xs:enumeration value="gloves" />
            
            <xs:enumeration value="potion" />
            <xs:enumeration value="provision" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>

      <xs:attribute name="weaponSubType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="weakBlunt" />
            <xs:enumeration value="edged" />
            <xs:enumeration value="blunt" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>

      <xs:attribute name="staminaDamage" type="xs:int" />
      <xs:attribute name="skillDamage" type="xs:int" />
      
      <xs:attribute name="dose" type="xs:int" />
      <xs:attribute name="price" type="xs:int" />

      <xs:attribute name="addToSkill" type="xs:int" />
      <xs:attribute name="addToStamina" type="xs:int" />
      <xs:attribute name="addToStaminaNd6" type="xs:int" />
      <xs:attribute name="addToLuck" type="xs:int" />
      <xs:attribute name="addToInitialSkill" type="xs:int" />
      <xs:attribute name="addToInitialStamina" type="xs:int" />
      <xs:attribute name="addToInitialLuck" type="xs:int" />
      <xs:attribute name="addToAttackStrength" type="xs:int" />
      <xs:attribute name="backpackSize" type="xs:int" />

      <xs:attribute name="magical" type="xs:boolean" default="false" />
      <xs:attribute name="blessed" type="xs:boolean" default="false" />

      <xs:attribute name="forceEquip" type="xs:boolean" default="false" />
      <xs:attribute name="removable" type="xs:boolean" default="true" />

      <xs:attribute name="actions" type="xs:integer" use="optional" default="1" />
      
      <xs:attribute name="preFight" type="xs:boolean" use="optional" default="false" />

    </xs:complexType>
  </xs:element>
</xs:schema>

=== melovictor/gamebooks/books/ff/tcoc/kjk6/src/main/resources/kjk6items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item id="defWpn" name="Ököl" type="weapon1" weaponSubType="weakBlunt" staminaDamage="2" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />


  <item id="stamina" name="Életerő Varázslat" type="common" />
  <item id="strength" name="Erő Varázslat" type="common" />
  <item id="weakness" name="Erőtlenség Varázslat" type="common" />
  <item id="foolsGold" name="Hamis Arany Varázslat" type="common" />
  <item id="illusion" name="Illúzió Varázslat" type="common" />
  <item id="esp" name="Különleges Érzékelő Készség Varázslat" type="common" />
  <item id="levitation" name="Súlytalanság Varázslat" type="common" />
  <item id="luck" name="Szerencse Varázslat" type="common" />
  <item id="creatureCopy" name="Teremtmény Hasonmás Varázslat" type="common" />
  <item id="fire" name="Tűz Varázslat" type="common" />
  <item id="skill" name="Ügyesség Varázslat" type="common" />
  <item id="shielding" name="Védelem Varázslat" type="common" />

</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk2items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-4" weaponSubType="weakBlunt" staminaDamage="2" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />


  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" />
  <item name="Ügyesség Itala" id="2001" type="potion" dose="2" addToSkill="12" />
  <item name="Erő Itala" id="2002" type="potion" dose="2" addToStamina="24" />
  <item name="Szerencse Itala" id="2003" type="potion" dose="2" addToLuck="12" addToInitialLuck="1" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />
  <item type="common" id="3002" name="Bronzkulcs" description="99" />
  <item type="common" id="3003" name="Láthatatlanság Itala" />
  <item type="gloves" id="3004" name="Selyemkesztyű" />
  <item type="shield" id="3005" name="Arany Félholdas Pajzs" />
  <item type="common" id="3006" name="Sajt" />
  <item type="common" id="3007" name="Íj és nyílvessző" />
  <item type="common" id="3008" name="Bronzkulcs" description="9"/>

  <item type="shadow" id="4001" name="+1 AS" addToAttackStrength="1" />
  <item type="shadow" id="4005" name="We won at least once against the old man"/>
  
  
</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/fh3items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Ököl" id="defWpn" type="weapon1" weaponSubType="weakBlunt" staminaDamage="2" removable="false" />
  <item name="Ököl" id="1000" type="weapon1" weaponSubType="weakBlunt" staminaDamage="2" forceEquip="true" />
  <item type="shooting" id="1001" name="Lézerkarabély" staminaDamage="4" forceEquip="true" />
  <item type="shooting" id="1002" name="Automata lézerkarabély" staminaDamage="6" forceEquip="true" />

  <item name="Egészségtabletta" id="2000" type="provision" addToStamina="6" />

  <item type="common" id="3001" name="Kézigránát" preFight="true" />
  <item type="common" id="3002" name="Kulcs" />
  <item type="common" id="3003" name="Satophil-D" />

  <item type="shadow" id="4001" name="Tudunk a C230-ról" />
  <item type="shadow" id="4002" name="Elpusztult az űrhajónk" />
  <item type="shadow" id="4003" name="Thuvald imája" />
  <item type="shadow" id="4004" name="Egy adag üzemanyag" />
  <item type="shadow" id="4005" name="Autó mocsaras" addToSkill="-1" />
</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjkz23items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Kard" id="allyWeapon" type="weapon1" staminaDamage="2" forceEquip="true" />
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-4" weaponSubType="weakBlunt" staminaDamage="2" removable="false" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />
  <item type="weapon1" id="1002" name="Mágikus Kard" weaponSubType="edged" staminaDamage="2" magical="true" />
  <item type="weapon1" id="1003" name="Éjcsillag" weaponSubType="edged" staminaDamage="2" magical="true" addToAttackStrength="1" />

  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" actions="2" />
  <item type="potion" id="2001" name="Brandy" dose="2" addToStamina="4" />
  <item type="potion" id="2002" name="Mágikus Gyógyfőzet" addToStamina="4" />
  <item type="potion" id="2003" name="Gyógyital" addToStamina="4" />
  <item type="potion" id="2004" name="Brandy" addToStamina="4" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />
  <item name="Lámpás" id="3002" type="common" />
  <item type="shield" id="3003" name="Pajzs" forceEquip="true" />
  <item type="necklace" id="3004" name="Fokhagymafüzér" forceEquip="true" />
  <item type="common" id="3005" name="Heydrich Amulet" price="3" />
  <item type="common" id="3006" name="Ezüst karkötő" price="3" />
  <item type="common" id="3007" name="Kristályüvegcse" price="4" />
  <item type="shield" id="3008" name="Hit Pajzsa" />
  <item type="common" id="3009" name="Ezüst Kulcs" />
  <item type="common" id="3010" name="Evőeszközök" price="4" />
  <item type="common" id="3011" name="Ezüst Tükör" />
  <item type="common" id="3012" name="Gyógyítók Könyve" />
  <item type="common" id="3013" name="Kardok Könyve" />
  <item type="common" id="3014" name="Ékszerek" price="7" />
  <item type="common" id="3015" name="Ezüst Cövek" />
  <item type="common" id="3016" name="Lothar kulcscsomója" />
  <item type="common" id="3017" name="Kristálymadarak" price="3" />
  <item type="common" id="3018" name="Elf imalánc" />
  <item type="common" id="3019" name="Ezüst-ametiszt Melltű" price="2" />
  <item type="ring" id="3020" name="Regeneráló Gyűrű" />
  <item type="common" id="3021" name="Csecsebecsék" price="4" />
  <item type="common" id="3022" name="Szentent Víz" />
  <item type="common" id="3023" name="Levelek" />
  <item type="common" id="3024" name="Aranybross" price="7" />
  <item type="common" id="3025" name="Kriptakulcs" />
  <item type="armour" id="3026" name="Siegfried Láncinge" addToInitialSkill="1" addToSkill="1" />
  <item type="common" id="3027" name="Ezüst Kereszt" />

  <item type="shadow" id="4001" name="Második Farkas eltalált" />
  <item type="shadow" id="4002" name="Lassan ható méreg" addToInitialStamina="-1" />
  <item type="shadow" id="4003" name="Lidérc eltalált" />
  <item type="shadow" id="4004" name="Baobhan Sith átka" />
  <item type="shadow" id="4005" name="Automatikus sebesülés" />
  <item type="shadow" id="4006" name="+1 TE" addToAttackStrength="1" />
  <item type="shadow" id="4007" name="Megölni Lothart Katarina parancsára" />
  <item type="shadow" id="4008" name="Megölni Lothart Katarina kérésére" />
  <item type="shadow" id="4009" name="Békénhagyni Lothart" />
  <item type="shadow" id="4010" name="Túl sok italozás" />
  <item type="shadow" id="4011" name="Túl sok italozás" addToSkill="-1" />
  <item type="shadow" id="4012" name="Ránk tapadt a Menyét" />
  <item type="shadow" id="4013" name="Erős Csapás aktív" />
  <item type="shadow" id="4014" name="Jandor Nyila aktív" />
  <item type="shadow" id="4015" name="Zúzás aktív" />
  <item type="shadow" id="4016" name="Ki kell nyírni a nagy Thalost" />
  <item type="shadow" id="4017" name="Tovább adófka sírjához" />
  <item type="shadow" id="4018" name="Egy automata találat a grófnak" />
  <item type="shadow" id="4019" name="Koporsó kinyiffantva" />
  <item type="shadow" id="4020" name="Kiszabadítottuk a lányt" actions="2" />
  <item type="shadow" id="4021" name="Egyszer már ettünk" />
  <item type="shadow" id="4022" name="Csak egyszer csökken az ügyesség" />

  <item type="shadow" id="4101" name="Lassan Ható Méreg" />
  <item type="shadow" id="4102" name="Likantrópia" />
  <item type="shadow" id="4103" name="Holló Átka" />
  <item type="shadow" id="4104" name="Súlyos Likantrópia" />
  <item type="shadow" id="4105" name="Baobhan Sith Átka" addToSkill="-2" />
  <item type="shadow" id="4106" name="Gyógyító Átka" />
  <item type="shadow" id="4107" name="Denevér Átka" />

  <item type="shadow" id="4213" name="Erőfal" />
  <item type="shadow" id="4214" name="Erős Csapás" />
  <item type="shadow" id="4215" name="Jandor Nyila" />
  <item type="shadow" id="4216" name="Szerencsevarázs" />
  <item type="shadow" id="4217" name="Zúzás" />
  <item type="shadow" id="4218" name="Igaz Gyógyítás" />

</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk8items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Kard" id="allyWeapon" type="weapon1" staminaDamage="2" forceEquip="true" />
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-3" weaponSubType="weakBlunt" staminaDamage="2" removable="false" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />
  <item name="Harci kalapács" id="1002" type="weapon1" weaponSubType="blunt" staminaDamage="2" />
  <item name="Lándzsa" id="1003" type="weapon1" weaponSubType="edged" staminaDamage="2" />
  <item name="Tőr" id="1004" type="weapon1" weaponSubType="edged" staminaDamage="2" />
  <item name="Gyorsaság Kardja" id="1005" type="weapon1" addToSkill="1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />
  <item name="Pompás kard" id="1006" type="weapon1" addToSkill="1" />

  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" />
  <item name="Ügyesség Itala" id="2001" type="potion" dose="2" addToSkill="12" />
  <item name="Erő Itala" id="2002" type="potion" dose="2" addToStamina="24" />
  <item name="Szerencse Itala" id="2003" type="potion" dose="2" addToLuck="12" addToInitialLuck="1" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />
  <item name="Lámpás" id="3002" type="common" />
  <item name="Köpeny" id="3003" type="cloak" />
  <item name="Sózott hal" id="3004" type="provision" addToStamina="4" />
  <item name="Gyertyatartó" id="3005" type="common" />
  <item name="Gyertya" id="3006" type="common" />
  <item name="Furulya" id="3007" type="common" />
  <item name="Rovásíráros bot" id="3008" type="common" />
  <!-- Zöld jáde béka talizmán -->
  <item name="Bátorság Amulettje" id="3009" type="necklace" forceEquip="true" addToSkill="2" />
  <item name="Vaskulcs" id="3010" type="common" />
  <item name="Parittya" id="3011" type="common" />
  <item name="Vasgolyó" id="3012" type="common" />
  <item name="Aranygyűrű" id="3013" type="ring" forceEquip="true" />
  <item name="Rézgyűrű" id="3014" type="ring" forceEquip="true" />
  <item name="Őrölt Minótaurusz-szarv" id="3015" type="common" />
  <item name="Fokhagyma" id="3016" type="common" />
  <item name="Fogas doboz" id="3017" type="common" />
  <item name="Pácolt gyíkfarok" id="3018" type="common" />
  <item name="Sárkánytojás" id="3019" type="common" />
  <item name="Fémkorong" id="3020" type="common" />
  <item name="Elf-Ősök Csizmája" id="3021" type="boots" />
  <item name="Fémcsillag" id="3022" type="common" />
  <item name="Fémnégyzet" id="3023" type="common" />
  <item name="Pajzs" id="3024" type="shield" addToSkill="1" forceEquip="true" />
  <item name="Szarvas Sisak" id="3025" type="helmet" />
  <item name="Tűzszerszám" id="3026" type="common" />
  <item name="Ezüst nyílhegy" id="3027" type="common" />
  <item name="Réz karpánt" id="3028a" type="bracelet" addToSkill="1" forceEquip="true" />
  <item name="Réz karpánt" id="3028b" type="bracelet" addToSkill="1" />

  <item type="shadow" id="4100" name="-2 támadóerő" addToAttackStrength="-2" />
</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjkzf2p1items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item id="defWpn" name="Ököl" type="weapon1" staminaDamage="2" addToSkill="-3" removable="false" />
  <item id="1001" name="Kard" type="weapon1" staminaDamage="2" forceEquip="true" />
  <item type="weapon1" id="3003" name="Szigony" weaponSubType="edged" staminaDamage="2" />
  <item type="weapon1" id="1004" name="Dárda" weaponSubType="edged" addToSkill="1" addToInitialSkill="1" staminaDamage="1" forceEquip="true" />

  <item type="provision" id="2000" name="Élelmiszer" addToStamina="4" />
  <item name="Ügyesség Itala" id="2001" type="potion" dose="2" addToSkill="12" />
  <item name="Erő Itala" id="2002" type="potion" dose="2" addToStamina="24" />
  <item name="Szerencse Itala" id="2003" type="potion" dose="2" addToLuck="12" addToInitialLuck="1" />

  <item type="shield" id="3001" name="Pajzs" forceEquip="true" />
  <item type="armour" id="3002" name="Bőrvért" forceEquip="true" />
  <item type="common" id="1002" name="Ékköves tőr" />
  <item type="common" id="3004" name="Kőszilánk" />
  <item type="common" id="3005" name="Csontdarab" />
  <item type="common" id="3006" name="Mágikus Kötél" />
  <item type="common" id="3007" name="Bőr" />
  <item type="common" id="3008" name="Vörös toll" />
  <item type="common" id="3009" name="Jeti karom" />
  <item type="bracelet" id="3010" name="Fém talizmán" forceEquip="true" />
  <item type="common" id="3011" name="Gyémánt" />
  <item type="common" id="3012" name="Bőr erszény" />
  <item type="common" id="3013" name="Arany kötél" />
  <item type="common" id="3014" name="Furulya" />
  <item type="common" id="3015" name="Átalakító Ital" />
  <item type="common" id="3016" name="Fülvédő" />
  <item type="common" id="3017" name="Kígyóbőr" />
  <item type="necklace" id="3018" name="Rubin medál" />
  <item type="common" id="3019" name="Fa szálka" />
  <item type="common" id="3020" name="Arany toll" />

  <item type="shadow" id="4001" name="Small Jeti hit us" />
</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk4items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-3" weaponSubType="weakBlunt" staminaDamage="2" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />
  <item type="weapon1" id="1002" name="Kardcsonk" weaponSubType="edged" staminaDamage="2" forceEquip="true" addToSkill="-2" />
  <item type="weapon1" id="1003" name="Mesterkard" weaponSubType="edged" staminaDamage="2" forceEquip="true" addToInitialSkill="2" />

  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" />
  <item name="Ügyesség Itala" id="2001" type="potion" dose="2" addToSkill="12" />
  <item name="Erő Itala" id="2002" type="potion" dose="2" addToStamina="24" />
  <item name="Szerencse Itala" id="2003" type="potion" dose="2" addToLuck="12" addToInitialLuck="1" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />
  <item name="Lámpás" id="3002" type="common" />
  <item type="common" id="3003" name="Vasrúd" />
  <item type="common" id="3004" name="Dárda" />
  <item type="necklace" id="3005" name="Csontamulett" />
  <item type="common" id="3006" name="Drót" />
  <item type="common" id="3007" name="Kisbalta" />
  <item type="common" id="3008" name="Tekercs kötél" />
  <item type="helmet" id="3009" name="Sog Sisakja" forceEquip="true" />
  <item type="common" id="3010" name="Aranyrög" />
  <item type="common" id="3011" name="Figyelmeztető cédula"
    description="Ha a kezedbe kerül ez az írás, az azt jelenti, hogy nem sikerült megszabadulnom a Gyíkkirály rabszolgabányájából. Tutajom a szurdok mögött van elrejtve, a folyóparton. Ha azért jöttél a szigetre, hogy segíts nekünk, kérlek, hajózz fölfelé a folyón egészen addig, míg meg nem pillantod sárkunyhóinkat. A rabszolgabányák közel vannak, de óvakodj a Gyíkember őreitől." />
  <item type="boots" id="3012" name="Csizma" />
  <item type="common" id="3013" name="Feneketlen Zsák" />
  <item type="ring" id="3014" name="Ügyetlenség Gyűrűje" addToSkill="-2" removable="false" forceEquip="true" />
  <item type="common" id="3015" name="Vaskulcsok" />
  <item type="common" id="3016" name="Vadászkürt" />
  <item type="common" id="3017" name="Kővé dermedt Grannitusz" />
  <item type="common" id="3018" name="Rézsíp" />
  <item type="common" id="3019" name="Toll" />

  <item type="shadow" id="4001" name="-1 Attack Strength" addToAttackStrength="-1" />
  <item type="shadow" id="4002" name="Lost against giant wasp" />
  <item type="shadow" id="4003" name="Succeeded on a Shaman-trial" />

</items>
