=== melovictor/gamebooks/core/support/src/main/resources/xsds/ff-items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gamebooks.zagor.hu" version="1.0" xmlns="http://gamebooks.zagor.hu">
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="item" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="item">
    <xs:complexType>
      <xs:attribute name="id" type="xs:string" use="required" />
      <xs:attribute name="name" type="xs:string" use="required" />

      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="common" />
            <xs:enumeration value="info" />
            <xs:enumeration value="shadow" />
            <xs:enumeration value="immediate" />

            <xs:enumeration value="weapon1" />
            <xs:enumeration value="weapon2" />
            <xs:enumeration value="shooting" />
            <xs:enumeration value="shield" />
            <xs:enumeration value="ring" />
            <xs:enumeration value="necklace" />
            <xs:enumeration value="boots" />
            <xs:enumeration value="armour" />
            <xs:enumeration value="helmet" />
            <xs:enumeration value="bracelet" />
            <xs:enumeration value="cloak" />
            <xs:enumeration value="brooch" />
            <xs:enumeration value="gloves" />
            
            <xs:enumeration value="potion" />
            <xs:enumeration value="provision" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>

      <xs:attribute name="weaponSubType">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="weakBlunt" />
            <xs:enumeration value="edged" />
            <xs:enumeration value="blunt" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>

      <xs:attribute name="staminaDamage" type="xs:int" />
      <xs:attribute name="skillDamage" type="xs:int" />
      
      <xs:attribute name="dose" type="xs:int" />
      <xs:attribute name="price" type="xs:int" />

      <xs:attribute name="addToSkill" type="xs:int" />
      <xs:attribute name="addToStamina" type="xs:int" />
      <xs:attribute name="addToStaminaNd6" type="xs:int" />
      <xs:attribute name="addToLuck" type="xs:int" />
      <xs:attribute name="addToInitialSkill" type="xs:int" />
      <xs:attribute name="addToInitialStamina" type="xs:int" />
      <xs:attribute name="addToInitialLuck" type="xs:int" />
      <xs:attribute name="addToAttackStrength" type="xs:int" />
      <xs:attribute name="backpackSize" type="xs:int" />

      <xs:attribute name="magical" type="xs:boolean" default="false" />
      <xs:attribute name="blessed" type="xs:boolean" default="false" />

      <xs:attribute name="forceEquip" type="xs:boolean" default="false" />
      <xs:attribute name="removable" type="xs:boolean" default="true" />

      <xs:attribute name="actions" type="xs:integer" use="optional" default="1" />
      
      <xs:attribute name="preFight" type="xs:boolean" use="optional" default="false" />

    </xs:complexType>
  </xs:element>
</xs:schema>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk15items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-4" weaponSubType="weakBlunt" staminaDamage="2" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />
  <item type="common" id="1002" name="Mágikus íj" />
  <item type="weapon1" id="1003" name="Lidérckard" addToInitialSkill="1" addToSkill="1" />
  <item type="weapon1" id="1004" name="Lándzsa" />


  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" />
  <item name="Ügyesség Itala" id="2001" type="potion" dose="1" addToSkill="12" />
  <item name="Erő Itala" id="2002" type="potion" dose="1" addToStamina="24" />
  <item name="Szerencse Itala" id="2003" type="potion" dose="1" addToLuck="12" addToInitialLuck="1" />
  <item name="Szerencse Itala" id="2004" type="potion" dose="1" addToLuck="12" />
  <item name="Gyógyital" id="2005" type="potion" dose="1" addToStamina="6" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />
  <item type="helmet" id="3002" name="Sisak" forceEquip="true" />
  <item type="common" id="3003" name="Sóska" />
  <item type="common" id="3004" name="Kulacs" />
  <item type="common" id="3005" name="Kötél" />
  <item type="ring" id="3006" name="Gránátgyűrű" />
  <item type="common" id="3007" name="Kristálytükör" />
  <item type="common" id="3008" name="Rézérc" />
  <item type="common" id="3009" name="Csákány" />
  <item type="common" id="3010" name="Vörösréz fülbevaló" />
  <!-- 8 mag, 11 sárkány -->
  <item type="common" id="3011" name="Snattamacska agyar" />
  <item type="common" id="3012" name="Bőrszütyő" />
  <!-- aka. Cholumbara -->
  <item type="common" id="3013" name="Kő istenszobor" />
  <item type="common" id="3014" name="Jogar" />
  <item type="common" id="3015" name="Tigriskarom" />
  <item type="common" id="3016" name="Hever Kürtje" preFight="true" />
  <item type="common" id="3017" name="Pillanatnyi Láthatatlanság Köpenye" />
  <item type="common" id="3018" name="Fagykenőcs" />
  <item type="boots" id="3019" name="Fürgeség Csizmája" />
  <item type="common" id="3020" name="Ékköves Nyakpánt" />
  <item type="cloak" id="3021" name="Vadmacska Bunda" />
  <!-- 21 -->
  <item type="common" id="3023" name="Országalma" />
  <item type="boots" id="3024" name="Hótalp" />


  <item type="shadow" id="4001" name="Can ask for Galrin's help" />
  <item type="shadow" id="4002" name="Not eaten in a given amount of time" />
  <item type="shadow" id="4003" name="Marker for food purchase" />
  <item type="shadow" id="4004" name="Hit the peasants" />
  <item type="shadow" id="4005" name="First Mordida is rabbid" />
  <item type="shadow" id="4006" name="Reset skill" />
  <item type="shadow" id="4007" name="Reset stamina" />
  <item type="shadow" id="4008" name="Reset luck" />
  <item type="shadow" id="4009" name="Unbound" />
  <item type="shadow" id="4010" name="Snow Cub's first hit" />
  <item type="shadow" id="4011" name="Cursed by Morgana" />

  <!-- Garlin: 100 // 85, 346 -->
  <!-- Új kulacs ha van, 2000 stamina 4 -->

</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk10items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-3" weaponSubType="weakBlunt" staminaDamage="2" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />
  <item type="weapon1" id="1002" name="Tőr" weaponSubType="edged" staminaDamage="2" addToSkill="-2" />
  <item type="weapon1" id="1003" name="Szent Kard" weaponSubType="edged" staminaDamage="2" addToSkill="1"/>

  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" />
  <item name="Ügyesség Itala" id="2001" type="potion" dose="1" addToSkill="12" />
  <item name="Erő Itala" id="2002" type="potion" dose="1" addToStamina="24" />
  <item name="Szerencse Itala" id="2003" type="potion" dose="1" addToLuck="12" addToInitialLuck="1" />
  <item type="provision" id="2004" name="Alma" addToStamina="4" />
  <item type="provision" id="2005" name="Fűz nedve" addToStamina="4" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />
  <item name="Lámpás" id="3002" type="common" />
  <item type="necklace" id="3003" name="Haláltalizmán" />

  <item type="shadow" id="4001" name="Captain critical hit" />
  <item type="shadow" id="4002" name="Death Knight battle is bad" />


</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk13items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item id="defWpn" name="Ököl" type="weapon1" weaponSubType="weakBlunt" staminaDamage="2" addToSkill="-2" removable="false" />
  <item type="weapon1" id="1001" name="Katana" weaponSubType="edged" staminaDamage="2" forceEquip="true" />
  <item type="weapon1" id="1002" name="Wakizashi" weaponSubType="edged" staminaDamage="2" addToSkill="-1" />
  <item type="weapon1" id="1003" name="Daloló Halál" weaponSubType="edged" staminaDamage="2" forceEquip="true" addToInitialLuck="2" addToLuck="2" addToInitialSkill="2" addToSkill="2" addToInitialStamina="4" addToStamina="4" />

  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" />
  <item type="potion" id="2001" name="Gyógyital" addToStamina="5" />

  <item name="Pajzs" id="3001" type="shield" forceEquip="true" />
  <item type="armour" id="3002" name="Páncélruha" forceEquip="true" damageProtection="2" />
  <item type="common" id="3003" name="A Shogun Pecsétje" removable="false" />
  <item type="common" id="3004" name="Szamurájíj" />
  <item type="common" id="3005" name="Shinmen fejkendője" />
  <item type="armour" id="3006" name="Szamurájpáncél" addToSkill="1" damageProtection="2" />
  <item type="common" id="3007" name="Vaslegyező" description="Fehér alapon kilenc arany nyílvessző mutat egy kék kör belseje felé." />
  <item type="common" id="3008" name="Zavarodottság Sisakja" />
  <item type="common" id="3009" name="Rézkulcs" addToSkill="-1" />
  <item type="common" id="3010" name="Pergamen" />
  <item type="common" id="3011" name="Selyemkép" />
  <item type="common" id="3012" name="Agancsdarab" />
  <item type="common" id="3013" name="Főnix alakú rubin" />
  <item type="necklace" id="3014" name="Váratlan Körülmények Talizmánja" />
  <item type="common" id="3015" name="Elefántcsont kürt" />
  <item type="armour" id="3016" name="A Hetedik Pecsét Seregének vértje" damageProtection="2" addToSkill="1" />
  <item type="common" id="3017" name="Fekete fabot" />
  <item type="common" id="3018" name="A Tudás Vize" />


  <item type="common" id="3101" name="Fűzlevelű vessző" description="2 [span class='ffAttribute']ÉLETERŐ[/span] pontot sebez" />
  <item type="common" id="3102" name="Bélfürkész vessző" description="3 [span class='ffAttribute']ÉLETERŐ[/span] pontot sebez" />
  <item type="common" id="3103" name="Páncéltörő vessző" description="2 [span class='ffAttribute']ÉLETERŐ[/span] pontot sebez, de csak bizonyos ellenfelekkel szemben hatásos" />
  <item type="common" id="3104" name="Süvítő gömb vessző" description="1 [span class='ffAttribute']ÉLETERŐ[/span] pontot sebez, de röptében félelmetes hangot ad" />
  <item type="common" id="3105" name="Tsunevara vessző" />

  <item type="shadow" id="4000" name="1 arrow against the Tiger" />
  <item type="shadow" id="4001" name="+1 attack strength" />
  <item type="shadow" id="4002" name="Killed first without suffering damage" />
  <item type="shadow" id="4003" name="Won the Tatsu" />
  <item type="shadow" id="4004" name="Won the Ki-Rin" />
  <item type="shadow" id="4005" name="Won the Tiger" />
  <item type="shadow" id="4006" name="Won the Phoenix" />
  <item type="shadow" id="4007" name="Won the Snake" />
  <item type="shadow" id="4008" name="Won the Golden Squadron" />
  <item type="shadow" id="4009" name="Won the Sorceress" />
  <item type="shadow" id="4010" name="Instant death at 27" />
  <item type="shadow" id="4011" name="Instant death at 199" />

</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk1items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-4" weaponSubType="weakBlunt" staminaDamage="2" removable="false" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />
  <item type="weapon1" id="1002" name="Opálgombos tőr" staminaDamage="2" weaponSubType="edged" addToSkill="-2" />
  <item type="weapon1" id="1003" name="Tőr" staminaDamage="2" weaponSubType="edged" addToSkill="-2" />
  <item type="weapon1" id="1004" name="Hosszú kés" staminaDamage="2" weaponSubType="edged" addToSkill="-2" />
  <item type="weapon1" id="1005" name="Görbe kard" staminaDamage="2" weaponSubType="edged" />


  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" />
  <item name="Ügyesség Itala" id="2001" type="potion" dose="1" addToSkill="12" />
  <item name="Erő Itala" id="2002" type="potion" dose="1" addToStamina="24" />
  <item name="Szerencse Itala" id="2003" type="potion" dose="1" addToLuck="12" addToInitialLuck="1" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />
  <item name="Lámpás" id="3002" type="common" />
  <item type="shield" id="3002a" name="Pajzs" forceEquip="true" />
  <item type="common" id="3003" name="Sav" />
  <item type="bracelet" id="3004" name="Csuklóvédő" addToSkill="-4" forceEquip="true" removable="false" />
  <item type="common" id="3005" name="Kötél" />
  <item type="common" id="3007" name="Facső" />
  <item type="common" id="3008" name="Smaragdszem" />
  <item type="ring" id="3009" name="Aranygyűrű" />
  <item type="common" id="3010" name="Rubingömb" />
  <item type="common" id="3011" name="Pergamen" />
  <item type="common" id="3012" name="Fakalapács" />
  <item type="common" id="3013" name="Vasszögek" />
  <item type="common" id="3014" name="Vaskulcs" />
  <item type="common" id="3015" name="Zafír" />
  <item type="common" id="3016" name="Topáz" />
  <item type="necklace" id="3017" name="Fognyaklánc" addToSkill="1" addToStamina="1" forceEquip="true" />
  <item type="ring" id="3018" name="Druida gyűrű" forceEquip="true" addToStamina="3" />
  <item type="armour" id="3019" name="Láncköpeny" addToSkill="1" />
  <item type="common" id="3020" name="Gyöngy" />
  <item type="common" id="3021" name="Gólyaláb" />
  <item type="common" id="3022" name="Gránát" />
  <item type="helmet" id="3023" name="Szárnyas Sisak" addToSkill="1" />
  <item type="common" id="3024" name="Hasonmás Ital" />
  <item type="common" id="3025" name="Tükör" />
  <item type="common" id="3026" name="Majom kabala" />
  <item type="common" id="3027" name="Csáklya" />
  <item type="common" id="3028" name="Rézcsengő" />
  <item type="common" id="3029" name="Csont" />
  <item type="common" id="3030" name="Leprechaun-fog" addToLuck="2" />
  <item type="shield" id="3031" name="Pajzs" addToSkill="1" />
  <item type="common" id="3032" name="Gyémánt" />

  <item type="shadow" id="4002" name="Attack Strength -2" addToAttackStrength="-2" />
</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/fh6items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item id="defWpn" name="Ököl" type="weapon1" weaponSubType="weakBlunt" staminaDamage="2" backpackSize="0" removable="false" />
  <item id="1000" name="Ököl" type="weapon1" weaponSubType="weakBlunt" staminaDamage="2" backpackSize="0" />
  <item type="weapon1" id="1001" name="Lézerkard" staminaDamage="2" forceEquip="true" />
  <item type="weapon1" id="1002" name="Lézerkarabély" />

  <item type="provision" id="2001" name="Gyümölcs" backpackSize="0" />
  <item type="provision" id="2002" name="Monyóka gyógyfőzet" backpackSize="0" />
  <item type="potion" id="2003" name="Gyógyital" addToStamina="4" />

  <item type="common" id="3001" name="Gomb" />
  <item type="common" id="3002" name="Benelo-foszfát gömb" />
  <item type="common" id="3003" name="Kéziduda" />
  <item type="common" id="3004" name="Nejlonkötél" />
  <item type="common" id="3005" name="Motorolaj" />
  <item type="common" id="3006" name="Üzenetrögzítő és manikűröző robot" />
  <item type="bracelet" id="3007" name="Zirídium karkötő" />
  <item type="common" id="3008" name="Infravörös pásztázó" />
  <item type="common" id="3009" name="Bárion-gránát" />
  <item type="common" id="3010" name="Kulcscsomó" />
  <item type="common" id="3011" name="Mágneslemezek" />
  <item type="common" id="3012" name="Drótvágó olló" />
  <item type="common" id="3013" name="Hátrakéta" />
  <item type="common" id="3014" name="Élelem" />
  <item type="common" id="3015" name="Bot" />
  <item type="common" id="3016" name="Agyszonda" />
  <item type="common" id="3017" name="Elmonit robbanóanyag" />
  <item type="common" id="3018" name="Fotongránát" />
  <item type="common" id="3019" name="Tapadóakna" />

  <item type="shadow" id="4001" name="Ettünk az első nap" />
  <item type="shadow" id="4366" name="Harc előtti teendők - 366" />
  <item type="shadow" id="4295" name="Harc előtti teendők - 295" />
  <item type="shadow" id="4256" name="Benzin és gömb egyben" />
  <item type="shadow" id="4351" name="Az Arkád köpött" />

  <item type="shadow" id="4002" name="Van egy megbeszélt időpontunk" />
  <item type="shadow" id="4003" name="-1 ügyesség" addToSkill="-1" />
  <item type="shadow" id="4004" name="Utcai Harcosról hallottunk" />
  <item type="shadow" id="4005" name="Eltörtük a botot" />
  <item type="shadow" id="4006" name="Még nem sebződtünk" />
  <item type="shadow" id="4007" name="Kitart az ügyesség-veszteség" />
  <item type="shadow" id="4008" name="Ismerjük a kódot" />

</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjk14items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-3" weaponSubType="weakBlunt" staminaDamage="2" forceEquip="true" />
  <item type="weapon1" id="1001" name="Papírvágó kés" staminaDamage="2" />
  <item type="weapon1" id="1002" name="Húsvágó kés" staminaDamage="2" />
  <item type="weapon1" id="1003" name="Ezüst tőr" addToSkill="-1" staminaDamage="2" />
  <item type="weapon1" id="1004" name="Deszka" staminaDamage="2" />
  <item type="weapon1" id="1005" name="Kés" staminaDamage="2" />
  <item type="weapon1" id="1006" name="Gyöngyháznyelű tőr" staminaDamage="2" />
  <item type="weapon1" id="1007" name="Kris tőr" staminaDamage="2" magical="true" />

  <item type="common" id="3001" name="Kötél" />
  <item type="common" id="3002" name="Fokhagyma" />
  <item type="ring" id="3003" name="Rubinköves aranygyűrű" />
  <item type="common" id="3004" name="Aranykulcs" />
  <!-- 27-es kulcs -->
  <item type="common" id="3005" name="Öntöttvas kulcs" />
  <item type="common" id="3006" name="Konyak" />
  <item type="necklace" id="3007" name="Talizmán" />
  <item type="common" id="3008" name="Könyv" />
  <item type="common" id="3009" name="Fekete folyadék" />

  <item type="shadow" id="4001" name="Támadóerő -2" addToAttackStrength="-2" />

  <item type="shadow" id="4002" name="Diabolus - 3" />
  <item type="shadow" id="4003" name="Drumer - 5" />

  <item type="shadow" id="4004" name="Azazel - 3" />
  <item type="shadow" id="4005" name="Abaddon - 5" />
  <item type="shadow" id="4006" name="Asmodeus - 3" />
  <item type="shadow" id="4007" name="Apollyon - 3" />

  <item type="shadow" id="4008" name="Kelnor - 5" />
  <item type="shadow" id="4009" name="Kris - 3" />

  <item type="shadow" id="4010" name="Mammon - 3" />
  <item type="shadow" id="4011" name="Mordana - 5" />

  <item type="shadow" id="4012" name="Shekou - 5" />
  <item type="shadow" id="4013" name="Shaitan - 3" />

  <item type="immediate" id="5001" name="Víz" addToStamina="2" />

  <item type="immediate" id="5002" name="Kenyér" addToStamina="2" />
  <item type="immediate" id="5003" name="Sütemény" addToStamina="2" />

  <item type="immediate" id="5004" name="Szárított hús" addToStamina="1" />
  <item type="immediate" id="5005" name="Szárított hal" addToStamina="1" />
  <item type="immediate" id="5006" name="Sajt" addToStamina="1" />

  <item type="immediate" id="5007" name="Fehér bor" addToSkill="-1" />
  <item type="immediate" id="5008" name="Vörös bor" addToSkill="-1" />

  <item type="immediate" id="5009" name="Gyümölcs" />

</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/kjkz27items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item name="Ököl" id="defWpn" type="weapon1" addToSkill="-4" weaponSubType="weakBlunt" staminaDamage="2" />
  <item name="Kard" id="1001" type="weapon1" forceEquip="true" weaponSubType="edged" staminaDamage="2" />

  <item name="Élelmiszer" id="2000" type="provision" addToStamina="4" />
  <item type="immediate" id="2001" name="Halpörkölt" addToStamina="4" />
  <item type="provision" id="2002" name="Szerencse Poros Szelence" addToLuck="1" />

  <item name="Bőrpáncél" id="3001" type="armour" forceEquip="true" />
  <item type="shield" id="3002" name="Pajzs" forceEquip="true" />
  <item type="common" id="3003" name="Rovarriasztó tégely" />
  <item type="common" id="3004" name="Üzenettekercs" description="A 3, 5, 0 számokat tudod csak kisilabizálni az írásból." />
  <item type="common" id="3005" name="Lámpás" />
  <item type="common" id="3006" name="Rózsavörös gyöngy" description="12 Aranytallér az értéke." />
  <item type="necklace" id="3007" name="Ezüstmedál" description="Egy nyitott tenyér van belevésve." />
  <item type="common" id="3008" name="Futás Itala" />

</items>

=== melovictor/gamebooks/books/ff/language-fightingfantasy/src/main/resources/fh1items.xml
<?xml version="1.0" encoding="utf-8" ?>
<items xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/ff-items.xsd">
  <item id="defWpn" name="Ököl" type="weapon1" weaponSubType="weakBlunt" staminaDamage="2" backpackSize="0" />
  <item type="weapon1" id="1001" name="Elektromos korbács" staminaDamage="2" backpackSize="0" />
  <item type="weapon1" id="1002" name="Plazmavető" staminaDamage="2" backpackSize="0" />

  <item type="provision" id="2000" name="Egészségtabletta" addToStamina="5" backpackSize="0" />
  <item type="provision" id="2001" name="Energiarúd" addToStamina="5" backpackSize="0.5" />
  <item type="provision" id="2002" name="Gyógytabletta" addToStamina="5" />

  <item type="common" id="3001" name="Gránát" backpackSize="0" />
  <item type="common" id="3002" name="Gravitációs bomba" backpackSize="0" />
  <item type="common" id="3003" name="Fekete szerkentyű" />
  <item type="common" id="3004" name="BIZ henger" />
  <item type="common" id="3005" name="Ideggáz" />
  <item type="common" id="3006" name="Ismeretlen tabletták" />
  <item type="common" id="3007" name="Döglött rák" />
  <item type="common" id="3008" name="Szerkentyű" />
  <item type="common" id="3009" name="Infravörös látókészülék" />
  <item type="common" id="3010" name="Kazetta" />
  <item type="common" id="3011" name="Csapágyas henger" />
  <item type="common" id="3012" name="Műanyag doboz" />
  <item type="common" id="3013" name="Kártyacsomag" />
  <item type="common" id="3014" name="Fekete folyadékos üvegcse" />
  <item type="common" id="3015" name="A Földöntúli Lények Enciklopédiája" />
  <item type="common" id="3016" name="Android fej" backpackSize="2" />
  <item type="common" id="3017" name="Gyümölcs" backpackSize="0" />

  <item type="shadow" id="4001" name="We have a squirell with us" />
  <item type="shadow" id="4999" name="Item that we will never have" />

</items>
