=== melovictor/gamebooks/core/support/src/main/resources/xsds/raw.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://gamebooks.zagor.hu" version="1.0" xmlns="http://gamebooks.zagor.hu">

  <xs:complexType name="randomType">
    <xs:choice minOccurs="1" maxOccurs="unbounded">
      <xs:element name="label" minOccurs="0" maxOccurs="1" type="xs:string" />
      <xs:element name="odd" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="loseBattleRound" minOccurs="0" maxOccurs="1">
              <xs:complexType></xs:complexType>
            </xs:element>
            <xs:group ref="descriptionGroup" minOccurs="0" maxOccurs="unbounded" />
          </xs:choice>
          <xs:attribute name="min" use="required" type="xs:string" />
          <xs:attribute name="max" use="required" type="xs:string" />
        </xs:complexType>
      </xs:element>
      <xs:element name="even" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="loseBattleRound" minOccurs="0" maxOccurs="1">
              <xs:complexType></xs:complexType>
            </xs:element>
            <xs:group ref="descriptionGroup" minOccurs="0" maxOccurs="unbounded" />
          </xs:choice>
          <xs:attribute name="min" use="required" type="xs:string" />
          <xs:attribute name="max" use="required" type="xs:string" />
        </xs:complexType>
      </xs:element>
      <xs:element name="result" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
          <xs:attribute name="min" use="required" type="xs:string" />
          <xs:attribute name="max" use="required" type="xs:string" />
          <xs:attribute name="allSame" use="optional" type="xs:boolean" />
        </xs:complexType>
      </xs:element>
      <xs:element name="resultElse" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
        </xs:complexType>
      </xs:element>
      <xs:element name="after" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
        </xs:complexType>
      </xs:element>
    </xs:choice>
    <xs:attribute name="diceConfig" type="xs:string">
      <xs:annotation>
        <xs:documentation>
          Must be the id of an existing DiceConfiguration bean in the spring application context without the 'dice' prefix. Some common dice configuration postfixes
          to use are '1d6' and '2d6', but custom ones can be referenced as well. The default is '1d6'.
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>


  <xs:element name="content">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="p">
          <xs:annotation>
            <xs:documentation>Defines a single paragraph of the book.</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="p">
    <xs:complexType>
      <xs:choice>
        <xs:element name="empty" minOccurs="1" maxOccurs="1">
          <xs:annotation>
            <xs:documentation>Defines that the given paragraph is nonexistent in the book.</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence />
          </xs:complexType>
        </xs:element>
        <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
      </xs:choice>
      <xs:attribute name="id" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation>Defines the name of the current paragraph.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="display" type="xs:string" use="optional">
        <xs:annotation>
          <xs:documentation>The displayed name of the current paragraph. If omitted, the id will be displayed.</xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:group name="descriptionGroup">
    <xs:choice>
      <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Defines the text of the given paragraph.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="reward">
        <xs:complexType>
          <xs:attribute name="id" use="required" type="xs:string" />
          <xs:attribute name="useSeriesId" use="optional" type="xs:boolean" default="false">
            <xs:annotation>
              <xs:documentation>
                Usually the system would send out the book's own ID to the server to register the reward. By setting this property to 'true' one can force the
                system to send out the ID of the series instead.
              </xs:documentation>
            </xs:annotation>
          </xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element name="codeword">
        <xs:complexType>
          <xs:attribute name="name" use="required" type="xs:string" />
        </xs:complexType>
      </xs:element>
      <xs:element name="next" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:annotation>
                <xs:documentation>Defines a continuation target.</xs:documentation>
              </xs:annotation>
              <xs:attribute name="id" type="xs:string" use="required">
                <xs:annotation>
                  <xs:documentation>Defines the number of the paragraph to turn to.</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:attribute name="pos" type="xs:integer" use="optional">
                <xs:annotation>
                  <xs:documentation>Defines the position of the given option element in the displayed list.</xs:documentation>
                </xs:annotation>
              </xs:attribute>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="gatherItem" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required">
          </xs:attribute>
          <xs:attribute name="amount" type="xs:integer" use="optional">
          </xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element name="loseItem" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required">
          </xs:attribute>
          <xs:attribute name="amount" type="xs:integer" use="optional">
          </xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element name="hideItem" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
          <xs:attribute name="amount" type="xs:integer" use="optional"></xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element name="unhideItem" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="id" type="xs:string" use="required"></xs:attribute>
          <xs:attribute name="amount" type="xs:integer" use="optional"></xs:attribute>
        </xs:complexType>
      </xs:element>
      <xs:element name="victory" minOccurs="0" maxOccurs="1">
        <xs:complexType></xs:complexType>
      </xs:element>
      <xs:element name="death" minOccurs="0" maxOccurs="1">
        <xs:complexType></xs:complexType>
      </xs:element>
      <xs:element name="itemCheck">
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="3">
            <xs:element name="have" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
              </xs:complexType>
            </xs:element>
            <xs:element name="haveEquipped" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
              </xs:complexType>
            </xs:element>
            <xs:element name="dontHave" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
              </xs:complexType>
            </xs:element>
            <xs:element name="after" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="type">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="section" />
                <xs:enumeration value="item" />
                <xs:enumeration value="codeword" />
                <xs:enumeration value="attribute" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="id" type="xs:string" />
          <xs:attribute name="amount" type="xs:integer" />
        </xs:complexType>
      </xs:element>


      <xs:element name="userInput" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="label" minOccurs="1" maxOccurs="1">
              <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="xs:string" />
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
            <xs:element name="result" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
                <xs:attribute name="text" type="xs:string" />
                <xs:attribute name="minResponse" type="xs:integer" use="optional" default="0">
                  <xs:annotation>
                    <xs:documentation>
                      The minimum amount of time that must elapse between the load of the page and the submission of the response in order to trigger this specific result.
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="maxResponse" type="xs:integer" use="optional" default="2147483647">
                  <xs:annotation>
                    <xs:documentation>
                      The maximum amount of time that can elapse between the load of the page and the submission of the response in order to trigger this specific result.
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="minBound" type="xs:integer" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      The lower bound of the user-providable amount range on which this response must react.
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
                <xs:attribute name="maxBound" type="xs:integer" use="optional">
                  <xs:annotation>
                    <xs:documentation>
                      The higher bound of the user-providable amount range on which this response must react.
                    </xs:documentation>
                  </xs:annotation>
                </xs:attribute>
              </xs:complexType>
            </xs:element>
            <xs:element name="resultElse" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:group ref="descriptionGroup" minOccurs="1" maxOccurs="unbounded" />
                <xs:attribute name="minResponse" type="xs:integer" use="optional" default="0" />
                <xs:attribute name="maxResponse" type="xs:integer" use="optional" default="2147483647" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="type" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="text" />
                <xs:enumeration value="number" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
          <xs:attribute name="min" use="optional" type="xs:integer" />
          <xs:attribute name="max" use="optional" type="xs:integer" />
        </xs:complexType>
      </xs:element>

      <xs:element name="random" maxOccurs="unbounded" minOccurs="0" type="randomType" />

    </xs:choice>
  </xs:group>
</xs:schema>

=== melovictor/gamebooks/books/gyg/language-giveyourselfgoosebumps/src/main/resources/gyg8content.xml
<?xml version="1.0" encoding="utf-8"?>
<content xmlns="http://gamebooks.zagor.hu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://gamebooks.zagor.hu http://zagor.hu/xsd/raw.xsd">
  <p id="back_cover">
    <text>
        [p]You're off to visit your grandmother, whose house hacks up to a graveyard. At first the tombstones seem far away. But every day they move a little closer. Then you discover the headstones are disappearing. But the dead aren't gone – their ghosts are moving. Right into your grandmother's house![/p]
        [p]If you decide to stay, you must battle a warrior ghost. If you decide to run, one of the kid ghosts follows you home. Will you be haunted... for the rest of your life?[/p]
    </text>
    <next id="background" />
  </p>
  <p id="background" display="Background">
    <text>
        [p]You can’t believe it! You stare out the window at the creepy cemetery in your grandmother’s backyard. The graves are moving! You’re sure of it. Then you turn to see an even more frightening sight – your grandmother’s house is haunted by ghosts. Lots of ghosts. Evil ghosts who want you![/p]
        [p]Why are the creeping coffins creeping? Do you stay to find out or do you race home – even though a terrifying ghost is waiting for you there, too?[/p]
        [p]If you stay you discover that the coffins are spelling a message in the graveyard – a message that spells out your doom. Unless you can find the ghost who is the Keeper of the Sword, steal the sword, and plunge it into the grave of the MPG! What’s an MPG? You’ll have to find out for yourself – but hurry, the ghosts are moving closer and closer...[/p]
    </text>
    <next id="1"></next>
  </p>
  <p id="1">
    <text>
        [p]“I'm bored,” you moan. “I’m so bored, I could eat flies. Just to see how they taste.”[/p]
        [p]“Flies have germs,” your grandmother replies.[/p]
        [p]It is a hot, sticky day in the middle of July. You plop down into a creaky old chair in your grandmother’s kitchen. Your parents dropped you off yesterday, before they left for their vacation. And already you could die of boredom.[/p]
        [p]Your grandmother’s old dog, Sparkle, yawns loudly. He crawls under the table. Moments later, he begins to snore.[/p]
        [p]“I know just how you feel, Sparkle,” you say. You sigh loudly.[/p]
        [p]“Why don’t you go outside and find something to do?” your grandmother suggests. She looks up from the pie she’s baking and nods toward the backyard.[/p]
        [p]Go out there? you think. Into her backyard? No way.[/p]
        [p]You glance out the window. It’s probably ninety degrees in the shade, but you shiver. Your grandmother’s house is right in front of an old cemetery. Rows and rows of old, crumbling tombstones sit just beyond the edge of her backyard.[/p]
        [p]But that’s not what scares you.[/p]
        [p]What scares you is that the tombstones have been moving![/p]
    </text>
    <next id="2"></next>
  </p>
  <p id="2">
    <text>
        [p]You noticed it right after you arrived yesterday.[/p]
        [p]You saw the tombstones from your bedroom window on the second floor. You could tell some of the graves had cool carvings on them, so you decided to go outside and take a closer look.[/p]
        [p]But when you entered the graveyard, something was different. Strange.[/p]
        [p]Some of the graves were out of place.[/p]
        [p]Nah, can’t be, you told yourself. Graves don’t disappear.[/p]
        [p]But still...[/p]
        [p]From your bedroom window, you could have sworn there were six or seven graves in the back row.[/p]
        [p]Now there were only three![/p]
        [p]Nah.... You must have counted wrong. You decided to forget it and went to bed.[/p]
        [p]But when you woke up this morning and glanced out the window, the coffins had moved again.[/p]
        [p]Now there were ten in the back row! And the middle rows seemed more crowded. It almost looked as if some of the graves were moving forward and some of the graves were moving backward, and there was a big traffic jam in the center.[/p]
        [p]The coffins were rearranging themselves![/p]
        [p]But how? And why?[/p]
    </text>
    <next id="3"></next>
  </p>
  <p id="3">
    <text>
        [p]Your grandmother taps you on the shoulder. She snaps you out of your daydream. “Go on,” she says. “Go play outside.”[/p]
        [p]Outside? Out [em]there?[/em] You shudder as you glance out the kitchen window again. “Oh, no,” you cry. “It’s disappeared!”[/p]
        [p]“What’s disappeared?” your grandmother asks.[/p]
        [p]“The grave with the angel on it!” you screech, pointing out the window. “It’s gone!”[/p]
        [p]One headstone in particular caught your eye yesterday. It had an angel carving on it. The angel looked so realistic you practically believed she could fly away.[/p]
        [p]Did she?[/p]
        [p]Your grandmother peers out the kitchen window. “Don’t be a goose,” she scolds you. “That tombstone is still there.”[/p]
        [p]You don’t answer her. You can’t. Your heart is pounding crazily and your mouth has gone dry. You bolt out the back door. You’ve got to see for yourself.[/p]
        [p]But in the graveyard you discover that your grandmother is right. The tombstone with the angel isn’t gone.[/p]
        [p]It just moved![/p]
        [p]It had been in the last row. Now it’s up front.[/p]
        [p]I’m losing my mind, you think. Losing it completely.[/p]
        [p]Or are you?[/p]
        [p]Find it out.[/p]
    </text>
    <next id="4"></next>
  </p>
  <p id="4">
    <text>
        [p]You run back into the house shouting.[/p]
        [p]“Grandma!” you yell. “That grave with the angel on it –”[/p]
        [p]Your grandmother interrupts you. “You don’t have to shout, dear. The angel?” She looks up from her pie crust. “That’s a nice one. Let me see. Who was buried there? Oh, yes. That’s Elmyra Martin’s grave.”[/p]
        [p]Before you can explain about the moving gravestones, a voice on the far side of the room makes you jump. “The name is [em]Elvira[/em] Martin,” the voice says sharply. “Not Elmyra. You never [em]could[/em] get my name right!”[/p]
        [p]Your mouth drops open. A strange woman now stands in the doorway that leads from the kitchen into the hall.[/p]
        [p]A very strange woman. Because she isn’t a living, breathing woman. She’s a ghost![/p]
        [p]“Uh, Grandma... ?” you begin. But from the way your granny is humming to herself, you can tell she doesn’t hear or see this scary visitor.[/p]
        [p]“And don’t you stare at me, you little wretch,” the ghost says, pointing at you. “Or you’ll be sorry.”[/p]
        [p]What are you going to do? Suddenly you’re living in a haunted house![/p]
    </text>
    <next id="18">If you run outside</next>
    <next id="25">If you talk to the ghost</next>
  </p>
  <p id="5">
    <text>
        [p]To your amazement, it works! The horse grows smaller.[/p]
        [p]Hey – cool![/p]
        [p]You push the volume button down again. Like magic, the ghost-horse grows even smaller.[/p]
        [p]“Wow!” you shout. You start pushing other buttons on the TV remote control. You can hardly wait to see what will happen![/p]
        [p]Unbelievably, when you press the channel button – the one that moves up to the next channel _ the ghost-horse changes into something else! A ghostly kung-fu master![/p]
        [p]When you press the button again, the kung-fu ghost changes into the ghost of an Egyptian pharaoh.[/p]
        [p]“This is amazing!” you exclaim.[/p]
        [p]Then you press it one more time.[/p]
        [p]Uh-oh. Big mistake.[/p]
    </text>
    <next id="129"></next>
  </p>
  <p id="6">
    <text>
        [p]You turn and run from Lark. But he’s gaining on you. And his friends have joined in the chase.[/p]
        [p]“Let’s get those little creeps!” Lark’s friends are shouting.[/p]
        [p]You and Robin are skidding around a corner when you hear a voice whisper in your ear. “I’ll help you – on one condition. You have to promise to do whatever I ask tomorrow.”[/p]
        [p]It’s the ghost-boy! You can’t see him, but you heard his offer. What are you going to do?[/p]
    </text>
    <next id="52">If you accept the ghost’s offer</next>
    <next id="59">If not</next>
  </p>
  <p id="7">
    <text>
        [p]Yuck! Everything in the bucket spills all over your hair, head, face, shoulders, and shirt.[/p]
        [p]Raw eggs. Warm soda. Sour milk. Bread[/p]
        [p]crumbs. It’s disgusting.[/p]
        [p]Some used tissues are mixed in there, too.[/p]
        [p]“What did you do that for?” you yell angrily.[/p]
        [p]“You saw the sign,” Digger replies. “No trespassers. That means [em]you[/em].”[/p]
        [p]What a creep! you think. Digger is a total, certified jerk.[/p]
        [p]In other words, he’s just what you need to deal with this ghost![/p]
        [p]So what are you going to do? Keep climbing – and take your chances with Digger? Or face the ghost alone?[/p]
    </text>
    <next id="11">If you keep climbing</next>
    <next id="38">If you face the ghost alone</next>
  </p>
  <p id="8">
    <text>
        [p]The Luckmeyer twins? What are they up to now? you wonder.[/p]
        [p]As MacFarling drives off, you notice that the sky is growing dark. Night is falling and there’s a thin wispy ring of clouds around the moon.[/p]
        [p]An owl hoots nearby. Then it swoops towrard you! Its claws seem to be aimed right for your face![/p]
        [p]You duck – and feel the tip of its wing brush past your cheek. When you glance up, you notice a curtain moving in a window on the second floor of your grandmother’s house.[/p]
        [p]There they are! That teenage ghost and his twin sister with the braids wrapped around her head – Jane and John Luckmeyer! John points down at you and laughs evilly.[/p]
        [p]I hope [em]he’s[/em] not the Keeper of the Sword, you think.[/p]
